build_from:
  amd64: ghcr.io/papra-hq/papra:26.3.0-rootless
  aarch64: ghcr.io/papra-hq/papra:26.3.0-rootless
  armv7: ghcr.io/papra-hq/papra:26.3.0-rootless
labels:
  org.opencontainers.image.title: "Papra"
  org.opencontainers.image.description: "Minimal document management platform"
  org.opencontainers.image.source: "https://github.com/chWagnr/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
